### ISSUE TITLE
OutOfMemoryError when adding large files to zip

### ISSUE THREAD

**Issue by hilel14** [hilel14/iceberg#1]
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.nio.file.Files.read(Unknown Source)
        at java.nio.file.Files.readAllBytes(Unknown Source)
        at org.hilel14.iceberg.Archiver.add(Archiver.java:98)
        at org.hilel14.iceberg.Archiver.access$000(Archiver.java:23)
        at org.hilel14.iceberg.Archiver$Zipper.visitFile(Archiver.java:78)
        at org.hilel14.iceberg.Archiver$Zipper.visitFile(Archiver.java:62)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at org.hilel14.iceberg.Archiver.createArchive(Archiver.java:53)
        at org.hilel14.iceberg.cli.Backup.startJob(Backup.java:66)
        at org.hilel14.iceberg.cli.Backup.main(Backup.java:34)
```

**Comment by hilel14** [comment]
fixed in commit 34298e5540f358d1b2ccb5b18733d1e338ee45ef
